# Home
home_index:
    path:       /
    controller: HomeController::home
    methods:    GET

# Post
post_index:
    path:       /posts
    controller: PostController::posts
    methods:    GET
post_show:
    path:       /post/{id}/{slug}
    controller: PostController::show
    methods:    GET
post_comment:
    path:       /post/{id}/{slug}/new-comment
    controller: PostController::newComment
    methods:    POST
post_comment_show_edit:
    path:       /post/{id}/{slug}/edit-comment/{idcomment}
    controller: PostController::showEditComment
    methods:    GET
post_comment_edit:
    path:       /post/{id}/{slug}/edit-comment/{idcomment}
    controller: PostController::editComment
    methods:    POST
post_category:
    path:       /post/category/{id}/{slug}
    controller: PostController::category
    methods:    GET
post_moderation_reported:
    path:       /post/{id}/{slug}/reported/{idcomment}
    controller: PostController::reported
post_like:
    path:       /post/{id}/{slug}/like
    controller: PostController::like
    methods:    GET
post_unlike:
    path:       /post/{id}/{slug}/unlike
    controller: PostController::unlike
    methods:    GET

# User account | profile
account_index:
    path:       /account
    controller: AccountController::account
    methods:    GET
account_show_edit_email:
    path:       /account/email/edit/{id}
    controller: AccountController::showEditEmail
    methods:    GET
account_edit_email:
    path:       /account/email/edit/{id}
    controller: AccountController::editEmail
    methods:    POST
account_show_edit_password:
    path:       /account/password/edit/{id}
    controller: AccountController::showEditPassword
    methods:    GET
account_edit_password:
    path:       /account/password/edit/{id}
    controller: AccountController::editPassword
    methods:    POST
account_show_edit_picture:
    path:       /account/picture/edit/{id}
    controller: AccountController::showEditPicture
    methods:    GET
account_edit_picture:
    path:       /account/picture/edit/{id}
    controller: AccountController::editPicture
    methods:    POST

profile_index:
    path:       /profile/{id}
    controller: ProfileController::showProfile
    methods:    GET

# Admin Dashboard
admin_dashboard:
    path:       /admin
    controller: AdminDashboardController::dashboard
    methods:    GET

# Admin Post
admin_post_index:
    path:       /admin/posts
    controller: AdminPostController::posts
    methods:    GET
admin_post_show_new:
    path:       /admin/post/new
    controller: AdminPostController::showNew
    methods:    GET
admin_post_new:
    path:       /admin/post/new
    controller: AdminPostController::new
    methods:    POST
admin_post_show_edit:
    path:       /admin/post/edit/{id}
    controller: AdminPostController::showEdit
    methods:    GET
admin_post_edit:
    path:       /admin/post/edit/{id}
    controller: AdminPostController::edit
    methods:    POST
admin_post_delete:
    path:       /admin/post/delete/{id}
    controller: AdminPostController::delete
admin_post_comment:
    path:       /admin/post/{id}/comments
    controller: AdminPostController::comments
    methods:    GET
admin_post_comment_delete:
    path:       /admin/post/{id}/comment/delete/{idcomment}
    controller: AdminPostController::deleteComment

# Admin moderation
admin_moderation_show_publication:
    path:       /admin/moderation/comment-publication/{id}
    controller: AdminModerationController::showPublication
    methods:    GET
admin_moderation_show_moderated:
    path:       /admin/moderation/comment-moderated/{id}
    controller: AdminModerationController::showModerated
    methods:    GET
admin_moderation_show_reported:
    path:       /admin/moderation/comment-reported/{id}
    controller: AdminModerationController::showReported
    methods:    GET
admin_moderation_publicated:
    path:       /admin/moderation/publicated/{id}
    controller: AdminModerationController::publicated
admin_moderation_moderated:
    path:       /admin/moderation/moderated/{id}
    controller: AdminModerationController::moderated
admin_moderation_delete:
    path:       /admin/moderation/delete/{id}
    controller: AdminModerationController::delete

# Admin Categories
admin_category_index:
    path:       /admin/categories
    controller: AdminCategoryController::categories
    methods:    GET
admin_category_show_new:
    path:       /admin/category/new
    controller: AdminCategoryController::showNew
    methods:    GET
admin_category_new:
    path:       /admin/category/new
    controller: AdminCategoryController::new
    methods:    POST
admin_category_show_edit:
    path:       /admin/category/edit/{id}
    controller: AdminCategoryController::showEdit
    methods:    GET
admin_category_edit:
    path:       /admin/category/edit/{id}
    controller: AdminCategoryController::edit
    methods:    POST
admin_category_delete:
    path:       /admin/category/delete/{id}
    controller: AdminCategoryController::delete

# Admin users
admin_user_index:
    path:       /admin/users
    controller: AdminUserController::users
    methods:    GET
admin_user_show_edit:
    path:       /admin/user/edit/{id}
    controller: AdminUserController::showEdit
    methods:    GET
admin_user_edit:
    path:       /admin/user/edit/{id}
    controller: AdminUserController::edit
    methods:    POST
admin_users_delete:
    path:       /admin/user/delete/{id}
    controller: AdminUserController::delete

# Admin roles
admin_role_index:
    path:       /admin/roles
    controller: AdminRoleController::roles
    methods:    GET
admin_role_show_new:
    path:       /admin/role/new
    controller: AdminRoleController::showNew
    methods:    GET
admin_role_new:
    path:       /admin/role/new
    controller: AdminRoleController::new
    methods:    POST
admin_role_show_edit:
    path:       /admin/role/edit/{id}
    controller: AdminRoleController::showEdit
    methods:    GET
admin_role_edit:
    path:       /admin/role/edit/{id}
    controller: AdminRoleController::edit
    methods:    POST
admin_role_delete:
    path:       /admin/role/delete/{id}
    controller: AdminRoleController::delete

# Authentication
authentication_index:
    path:       /login
    controller: AuthenticationController::showLogin
    methods:    GET
authentication_login:
    path:       /login
    controller: AuthenticationController::login
    methods:    POST
authentication_logout:
    path:       /logout
    controller: AuthenticationController::logout

# Register
register_index:
    path:       /register
    controller: RegisterController::showRegister
    methods:    GET
register:
    path:       /register
    controller: RegisterController::register
    methods:    POST
    