home_index:
    path:       /
    controller: HomeController::home
    methods:    GET
post_index:
    path:       /posts
    controller: PostController::posts
    methods:    GET
post_show:
    path:       /post/{id}/{slug}
    controller: PostController::show
    methods:    GET

